// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDNvo14Ea7sw2eCUYmRjD3OPsGB0R1Buw',
    appId: '1:129219992136:web:4a79ee488a3fc8792c967d',
    messagingSenderId: '129219992136',
    projectId: 'kolaytarifler-37c45',
    authDomain: 'kolaytarifler-37c45.firebaseapp.com',
    storageBucket: 'kolaytarifler-37c45.firebasestorage.app',
    measurementId: 'G-HWJF64JFQ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXNV7RqM5Kk3D6y3SpwN4fE7VRBvpSH04',
    appId: '1:129219992136:android:8dd48b2448206af42c967d',
    messagingSenderId: '129219992136',
    projectId: 'kolaytarifler-37c45',
    storageBucket: 'kolaytarifler-37c45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQQp0-dhZHTCI3V-l8kmz-kL5T-vJmqJw',
    appId: '1:129219992136:ios:7655112eddbe532d2c967d',
    messagingSenderId: '129219992136',
    projectId: 'kolaytarifler-37c45',
    storageBucket: 'kolaytarifler-37c45.firebasestorage.app',
    iosBundleId: 'com.kolaytarifler.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQQp0-dhZHTCI3V-l8kmz-kL5T-vJmqJw',
    appId: '1:129219992136:ios:abed589ff31e3aa92c967d',
    messagingSenderId: '129219992136',
    projectId: 'kolaytarifler-37c45',
    storageBucket: 'kolaytarifler-37c45.firebasestorage.app',
    iosBundleId: 'com.kolaytarifler.app.macos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDNvo14Ea7sw2eCUYmRjD3OPsGB0R1Buw',
    appId: '1:129219992136:web:35722b35b5463a1b2c967d',
    messagingSenderId: '129219992136',
    projectId: 'kolaytarifler-37c45',
    authDomain: 'kolaytarifler-37c45.firebaseapp.com',
    storageBucket: 'kolaytarifler-37c45.firebasestorage.app',
    measurementId: 'G-4Q7ESSM2YE',
  );
}
