const i = (name, amount, emoji = '🍽️', category = 'other') => ({ name, amount, emoji, category });
const r = (name, description, type, emoji, duration, servings, tags, ingredients, steps) => ({
  name, description, type, emoji, duration, servings, tags, ingredients,
  steps: steps.map((text, index) => ({ order: index + 1, text })),
});

module.exports = [
  r('Ankara Tava', 'Kuzu eti ile arpa şehriyenin et suyunda ağır ağır piştiği Ankara mutfağının geleneksel fırın yemeği.', 'Ana Yemek', '🍖', '2 sa 30 dk', '6 kişilik', ['Ankara', 'Kuzu', 'Fırın', 'Geleneksel'], [
    i('Kuzu kol', '1 kg kemikli parça', '🍖', 'meat'), i('Arpa şehriye', '2 su bardağı', '🌾', 'grain'),
    i('Tereyağı', '3 yemek kaşığı', '🧈', 'dairy'), i('Domates', '2 adet', '🍅', 'vegetable'),
    i('Sivri biber', '3 adet', '🌶️', 'vegetable'), i('Sıcak su', '4 su bardağı', '💧', 'other'),
    i('Tuz', '1,5 tatlı kaşığı', '🧂', 'other'), i('Karabiber', '1 çay kaşığı', '🌶️', 'spice'),
  ], [
    'Kuzu etini iri porsiyonlara ayırın, fazla zarlarını temizleyip tuz ve karabiberle ovun.',
    'Eti kapaklı, fırına dayanıklı geniş bir kaba alın; 2 su bardağı sıcak su ekleyip 180°C fırında yaklaşık 90 dakika yumuşayana kadar pişirin.',
    'Pişen eti kaptan çıkarın ve dinlendirin; kapta kalan et suyunu süzüp ölçerek toplam 4 su bardağına sıcak suyla tamamlayın.',
    'Arpa şehriyeyi tereyağında orta ateşte renk alana kadar 5-6 dakika kavurun.',
    'Şehriyeyi fırın kabına yayın; doğranmış domates ve biberleri ekleyip sıcak et suyunu üzerine dökün.',
    'Et parçalarını şehriyenin üzerine yerleştirin ve kabı yeniden 190°C fırına verin.',
    'Şehriye suyu çekip yumuşayana kadar 25-30 dakika pişirin; fırından çıktıktan sonra 10 dakika dinlendirip servis edin.',
  ]),
  r('Ayvalık Tostu', 'Özel tost ekmeği, sucuk, salam, peynir, turşu ve Rus salatasıyla hazırlanan Ayvalık’ın bol malzemeli sokak lezzeti.', 'Atıştırmalık', '🥪', '25 dk', '2 kişilik', ['Ayvalık', 'Tost', 'Sokak Lezzeti', 'Pratik'], [
    i('Ayvalık tost ekmeği', '4 kalın dilim', '🍞', 'grain'), i('Kaşar peyniri', '120 g', '🧀', 'dairy'),
    i('Sucuk', '80 g ince dilim', '🥩', 'meat'), i('Dana salam', '60 g', '🥩', 'meat'),
    i('Domates', '1 adet', '🍅', 'vegetable'), i('Salatalık turşusu', '6 adet', '🥒', 'vegetable'),
    i('Rus salatası', '4 yemek kaşığı', '🥗', 'vegetable'), i('Tereyağı', '1 yemek kaşığı', '🧈', 'dairy'),
  ], [
    'Sucuk dilimlerini yağsız tavada iki yüzü hafif kızarana kadar pişirin; salamları da kısa süre ısıtın.',
    'Ekmek dilimlerinin dış yüzlerine ince bir tabaka tereyağı sürün.',
    'İki dilimin iç tarafına kaşar peyniri, sucuk ve salamı eşit biçimde yerleştirin.',
    'Tostları kapatıp önceden ısıtılmış tost makinesinde ekmek gevrekleşip peynir tamamen eriyene kadar bastırarak pişirin.',
    'Tostları açıp ince domates ve turşu dilimlerini ekleyin; Rus salatasını sıcak malzemenin üzerine yayın.',
    'Tostları tekrar kapatıp yalnızca 30 saniye bastırın; çapraz keserek sıcak servis edin.',
  ]),
  r('Bafra Pidesi', 'İnce ve uzun hamurun içine kavrulmuş kıymalı harç kapatılarak taş fırın usulü pişirilen Samsun pidesi.', 'Hamur İşi', '🥙', '1 sa 45 dk', '4 kişilik', ['Samsun', 'Pide', 'Kıymalı', 'Fırın'], [
    i('Un', '500 g', '🌾', 'grain'), i('Ilık su', '280 ml', '💧', 'other'), i('Kuru maya', '7 g', '🧂', 'other'),
    i('Dana kıyma', '400 g', '🥩', 'meat'), i('Kuru soğan', '2 adet', '🧅', 'vegetable'),
    i('Tereyağı', '3 yemek kaşığı', '🧈', 'dairy'), i('Tuz', '1,5 tatlı kaşığı', '🧂', 'other'),
    i('Karabiber', '1 çay kaşığı', '🌶️', 'spice'), i('Yumurta sarısı', '1 adet', '🥚', 'egg'),
  ], [
    'Un, maya, 1 tatlı kaşığı tuz ve ılık suyu birleştirip pürüzsüz, yumuşak bir hamur yoğurun.',
    'Hamurun üzerini kapatın ve hacmi iki katına çıkana kadar yaklaşık 50 dakika mayalandırın.',
    'Kıymayı tavada suyunu salıp çekene kadar kavurun; ince doğranmış soğanı, karabiberi ve kalan tuzu ekleyip soğutun.',
    'Hamuru dört bezeye ayırın; her bezeyi unlu zeminde yaklaşık 50 cm uzunluğunda, ince oval biçimde açın.',
    'Soğuk kıymalı harcı hamurun ortasına uzunlamasına yayın; iki uzun kenarı ortada birleştirip uçları sıkıca kapatın.',
    'Pideleri birleşim yeri alta gelecek şekilde tepsiye alın, üzerlerine yumurta sarısı sürün.',
    'Önceden ısıtılmış 240°C fırında 12-15 dakika kızarana kadar pişirin; çıkınca tereyağı sürüp dilimleyin.',
  ]),
  r('Bici Bici', 'Nişastalı muhallebi küpleri, gül kokulu şerbet ve ince rendelenmiş buzla hazırlanan Adana’nın ferahlatıcı yaz tatlısı.', 'Tatlı', '🍧', '3 sa', '6 kişilik', ['Adana', 'Soğuk Tatlı', 'Yaz', 'Gül Suyu'], [
    i('Buğday nişastası', '1 su bardağı', '🌾', 'grain'), i('Su', '6 su bardağı', '💧', 'other'),
    i('Toz şeker', '1 su bardağı', '🍬', 'other'), i('Gül suyu', '3 yemek kaşığı', '🌹', 'other'),
    i('Kırmızı gıda boyası', '2 damla, isteğe bağlı', '🔴', 'other'), i('Buz', '4 su bardağı kırılmış', '🧊', 'other'),
    i('Pudra şekeri', '4 yemek kaşığı', '🍬', 'other'),
  ], [
    'Nişastayı 1 su bardağı soğuk suyla topaksız olana kadar çırpın.',
    'Karışımı tencereye alın, 3 su bardağı su ekleyin ve orta ateşte sürekli karıştırarak koyu, saydam bir muhallebi kıvamına getirin.',
    'Muhallebiyi suyla ıslatılmış geniş kaba 2 cm kalınlığında dökün; soğutup buzdolabında en az 2 saat dinlendirin.',
    'Şerbet için şekeri 2 su bardağı suyla eritin; gül suyu ve istenirse gıda boyasını ekleyip tamamen soğutun.',
    'Donan muhallebiyi küçük küpler halinde kesin ve servis kaselerine paylaştırın.',
    'Üzerine çok ince kırılmış ya da rendelenmiş buzu yığın; soğuk gül şerbetini gezdirin.',
    'Pudra şekeri serperek bekletmeden servis edin.',
  ]),
  r('Boyoz', 'Kat kat yağlanıp rulo yapılan mayasız hamurdan hazırlanan İzmir’in çıtır dışlı, yumuşak içli kahvaltılık hamur işi.', 'Hamur İşi', '🥐', '3 sa', '8 kişilik', ['İzmir', 'Kahvaltı', 'Hamur İşi', 'Geleneksel'], [
    i('Un', '500 g', '🌾', 'grain'), i('Ilık su', '300 ml', '💧', 'other'), i('Tuz', '1 tatlı kaşığı', '🧂', 'other'),
    i('Ayçiçek yağı', '120 ml', '🫗', 'oil'), i('Tereyağı', '100 g eritilmiş', '🧈', 'dairy'),
    i('Limon suyu', '1 tatlı kaşığı', '🍋', 'fruit'),
  ], [
    'Un, su, tuz ve limon suyunu birleştirip ele yapışmayan, esnek bir hamur olana kadar yaklaşık 10 dakika yoğurun.',
    'Hamuru dört bezeye ayırın, yüzeylerini yağlayıp kapalı olarak 30 dakika dinlendirin.',
    'Her bezeyi yağlı tezgahta ellerinizle olabildiğince ince, neredeyse saydam bir yufka halinde esnetin.',
    'Yüzeye eritilmiş tereyağı ve ayçiçek yağı karışımı sürün; yufkayı karşılıklı kenarlardan katlayıp uzun rulo yapın.',
    'Ruloları kendi etrafında sarıp buzdolabında en az 1 saat dinlendirin.',
    'Hamurları 2-3 cm kalınlığında dilimleyin, kesik yüzey üste gelecek şekilde bastırıp yuvarlaklaştırın.',
    '220°C fırında kabarıp koyu altın rengi alana kadar 18-22 dakika pişirin; sıcak servis edin.',
  ]),
  r('Bursa Cantık', 'Ortası açık bırakılan yumuşak hamurun bol soğanlı kıymayla doldurulduğu Bursa’ya özgü küçük pide.', 'Hamur İşi', '🥙', '1 sa 40 dk', '6 kişilik', ['Bursa', 'Pide', 'Kıymalı', 'Fırın'], [
    i('Un', '500 g', '🌾', 'grain'), i('Ilık süt', '200 ml', '🥛', 'dairy'), i('Ilık su', '100 ml', '💧', 'other'),
    i('Kuru maya', '7 g', '🧂', 'other'), i('Dana kıyma', '350 g', '🥩', 'meat'),
    i('Kuru soğan', '2 adet', '🧅', 'vegetable'), i('Domates', '1 adet', '🍅', 'vegetable'),
    i('Sivri biber', '2 adet', '🌶️', 'vegetable'), i('Tereyağı', '2 yemek kaşığı', '🧈', 'dairy'),
  ], [
    'Un, maya, 1 tatlı kaşığı tuz, ılık süt ve suyu yoğurup yumuşak bir hamur hazırlayın.',
    'Hamuru kapalı olarak 45 dakika mayalandırın ve altı eşit bezeye ayırın.',
    'Kıyma, çok ince doğranmış soğan, domates ve biberi tuz-karabiberle çiğden karıştırın.',
    'Bezeleri 15 cm çapında açın; kenarlardan içe doğru kıvırıp ortası geniş ve açık küçük kayık şekli verin.',
    'Kıymalı harcı açık orta bölüme bastırarak yayın ve hamur kenarlarına eritilmiş tereyağı sürün.',
    '230°C fırında tabanı kızarıp kıyma pişene kadar 12-15 dakika pişirin.',
    'Fırından çıkan cantıkların kenarlarına yeniden az tereyağı sürüp sıcak servis edin.',
  ]),
  r('Büryan Kebabı', 'Kuzu etinin kapalı ve nemli tandır ortamında uzun süre pişirilmesiyle hazırlanan Bitlis ve Siirt’in geleneksel kebabı.', 'Ana Yemek', '🍖', '3 sa 30 dk', '6 kişilik', ['Bitlis', 'Siirt', 'Kuzu', 'Tandır'], [
    i('Kuzu kol', '1,5 kg kemikli', '🍖', 'meat'), i('Kaya tuzu', '2 tatlı kaşığı', '🧂', 'other'),
    i('Su', '2 su bardağı', '💧', 'other'), i('Tırnak pide', '2 adet', '🫓', 'grain'),
    i('Kuru soğan', '2 adet', '🧅', 'vegetable'), i('Sumak', '1 yemek kaşığı', '🌶️', 'spice'),
  ], [
    'Kuzu etinin fazla yağ ve zarlarını alın; iri parçaları kaya tuzuyla her tarafını kaplayacak biçimde ovun.',
    'Fırının alt rafına su dolu derin bir tepsi yerleştirin; böylece pişme boyunca nemli tandır ortamı oluşur.',
    'Eti tel ızgara üzerine koyup su tepsisinin üst rafına yerleştirin; 160°C fırında üzeri kapalı olarak 2 saat pişirin.',
    'Kapağı açın ve eti 190°C’de 45-60 dakika daha, dışı kızarıp kemikten kolay ayrılana kadar pişirin.',
    'Eti fırından çıkarıp 15 dakika dinlendirin, kemiklerinden ayırarak iri lifler halinde parçalayın.',
    'Pideleri fırında ısıtın; etin tepside biriken suyundan az miktarda üzerlerine gezdirin.',
    'Büryanı sıcak pide üzerinde, sumakla ovulmuş soğan eşliğinde servis edin.',
  ]),
  r('Ciğer Sarma', 'Kuzu ciğeri, pirinç ve baharatlı iç pilavın kuzu gömleğine sarılıp fırınlandığı Trakya yemeği.', 'Ana Yemek', '🍖', '1 sa 45 dk', '6 kişilik', ['Trakya', 'Ciğer', 'İç Pilav', 'Fırın'], [
    i('Kuzu gömleği', '1 adet', '🥩', 'meat'), i('Kuzu ciğeri', '500 g', '🍖', 'meat'),
    i('Pirinç', '1,5 su bardağı', '🍚', 'grain'), i('Kuru soğan', '2 adet', '🧅', 'vegetable'),
    i('Dolmalık fıstık', '2 yemek kaşığı', '🥜', 'nut'), i('Kuş üzümü', '2 yemek kaşığı', '🍇', 'fruit'),
    i('Tereyağı', '3 yemek kaşığı', '🧈', 'dairy'), i('Yenibahar', '1 çay kaşığı', '🌶️', 'spice'),
    i('Tarçın', 'yarım çay kaşığı', '🌿', 'spice'),
  ], [
    'Kuzu gömleğini ılık suda 15 dakika bekletip yumuşatın, ardından dikkatlice süzün.',
    'Pirinçleri yıkayıp 15 dakika ılık suda bekletin; kuş üzümünü ayrı kapta şişirin.',
    'Soğan ve dolmalık fıstığı tereyağında kavurun; küçük doğranmış ciğeri ekleyip yüksek ateşte 4-5 dakika çevirin.',
    'Pirinç, kuş üzümü, yenibahar, tarçın, tuz ve 2 su bardağı sıcak su ekleyip pilavı yarı diri kalacak şekilde pişirin.',
    'Kuzu gömleğini kaselerin içine paylaştırın, iç pilavı doldurup sarkan kenarları üstte kapatın.',
    'Sarmaları birleşim yeri alta gelecek şekilde fırın kabına dizin ve kaba yarım su bardağı sıcak su ekleyin.',
    '190°C fırında gömlek kızarıp iç pilav tamamen pişene kadar 35-40 dakika pişirin.',
  ]),
  r('Denizli Kebabı', 'Kuzu etinin taş fırında kendi yağı ve suyuyla ağır ağır piştiği, geleneksel olarak pide üzerinde sunulan Denizli kebabı.', 'Ana Yemek', '🍖', '3 sa', '6 kişilik', ['Denizli', 'Kuzu', 'Fırın', 'Geleneksel'], [
    i('Kuzu kol ve kaburga', '1,5 kg iri parça', '🍖', 'meat'), i('İç yağı', '100 g', '🥩', 'meat'),
    i('Tuz', '2 tatlı kaşığı', '🧂', 'other'), i('Su', '1,5 su bardağı', '💧', 'other'),
    i('Tırnak pide', '2 adet', '🫓', 'grain'), i('Domates', '3 adet', '🍅', 'vegetable'),
    i('Kuru soğan', '2 adet', '🧅', 'vegetable'),
  ], [
    'Kuzu etini iri kemikli parçalara ayırın; yıkamadan kâğıt havluyla kurulayın ve tuzlayın.',
    'Geniş döküm ya da kalın tabanlı fırın kabının altına iç yağını küçük parçalar halinde yayın.',
    'Etleri yağın üzerine tek kat yerleştirin ve kabın kenarından suyu ekleyin.',
    'Kabın üzerini sıkıca kapatıp 170°C fırında yaklaşık 2 saat pişirin.',
    'Kapağı açın; etleri çevirip 200°C’de 30-40 dakika dışı kızarana ve kemikten ayrılana kadar pişirin.',
    'Pideleri et suyuyla hafifçe ıslatıp fırında ısıtın; etleri iri parçalar halinde üzerlerine yerleştirin.',
    'Denizli usulü olarak çatal kullanmadan yenebilecek yumuşaklıkta, domates ve kuru soğanla servis edin.',
  ]),
  r('Döner Kebap', 'Terbiyelenmiş dana etinin kat kat dizilip dikey şişte çevrilerek kızartılmasıyla hazırlanan klasik Türk kebabı.', 'Ana Yemek', '🥙', '5 sa', '6 kişilik', ['Kebap', 'Dana Eti', 'Sokak Lezzeti', 'Geleneksel'], [
    i('Dana antrikot', '1 kg ince dilim', '🥩', 'meat'), i('Yoğurt', '4 yemek kaşığı', '🥛', 'dairy'),
    i('Kuru soğan suyu', '1 çay bardağı', '🧅', 'vegetable'), i('Zeytinyağı', '3 yemek kaşığı', '🫒', 'oil'),
    i('Domates salçası', '1 yemek kaşığı', '🍅', 'vegetable'), i('Kekik', '1 tatlı kaşığı', '🌿', 'spice'),
    i('Karabiber', '1 çay kaşığı', '🌶️', 'spice'), i('Tuz', '1,5 tatlı kaşığı', '🧂', 'other'),
  ], [
    'Eti kasabınıza liflere dik yönde çok ince yapraklar halinde kestirin ve yüzeyini kurulayın.',
    'Yoğurt, soğan suyu, zeytinyağı, salça, kekik ve karabiberi çırparak terbiyeyi hazırlayın.',
    'Et dilimlerini terbiyeyle kaplayın; kapalı kapta buzdolabında en az 4 saat dinlendirin.',
    'Dilimleri üst üste sıkıca yerleştirip silindir biçiminde streçleyin ve dondurucuda 45 dakika sertleştirin.',
    'Eti çok ince şeritler halinde kesin; geniş döküm tavayı duman çıkacak kadar ısıtın.',
    'Etleri tavayı doldurmadan partiler halinde, yüksek ateşte kenarları kızarana kadar pişirin ve son aşamada tuzlayın.',
    'Pişen etleri sıcak tutup pide, sumaklı soğan, közlenmiş domates ve biberle servis edin.',
  ]),
  r('Edirne Tava Ciğeri', 'İncecik kesilmiş dana ciğerinin una bulanıp kızgın yağda çıtırlaştırıldığı Edirne klasiği.', 'Ana Yemek', '🍖', '35 dk', '4 kişilik', ['Edirne', 'Ciğer', 'Kızartma', 'Geleneksel'], [
    i('Dana ciğeri', '700 g', '🥩', 'meat'), i('Un', '1 su bardağı', '🌾', 'grain'), i('Tuz', '1 tatlı kaşığı', '🧂', 'other'), i('Ayçiçek yağı', '3 su bardağı', '🫗', 'oil'), i('Kuru acı biber', '12 adet', '🌶️', 'spice'), i('Kuru soğan', '2 adet', '🧅', 'vegetable'), i('Sumak', '1 yemek kaşığı', '🌶️', 'spice'),
  ], [
    'Ciğerin zarını tamamen ayırın, damarlarını temizleyin ve yaprak inceliğinde şeritler halinde kesin.',
    'Ciğeri yıkamadan kâğıt havluyla iyice kurulayın; fazla nem kızartmanın çıtırlığını azaltır.',
    'Kuru biberleri az yağda kısa süre kızartıp yakmadan çıkarın ve servis için ayırın.',
    'Unu geniş bir kaba alın; ciğerleri una bulayıp süzgeçte silkeleyerek fazla unu uzaklaştırın.',
    'Yağı 180°C’ye getirin ve ciğerleri tavayı doldurmadan 45-60 saniyelik partiler halinde kızartın.',
    'Kızaran ciğerleri tel ızgaraya çıkarıp sıcakken tuzlayın; uzun bekletmeden servis tabağına alın.',
    'Sumakla ovulmuş soğan ve kızarmış kuru biberlerle hemen servis edin.',
  ]),
  r('Elbasan Tava', 'Kuzu etinin sarımsaklı yoğurt ve yumurtalı terbiye altında fırınlandığı Osmanlı mutfağı yemeği.', 'Ana Yemek', '🍖', '1 sa 40 dk', '6 kişilik', ['Osmanlı', 'Kuzu', 'Yoğurt', 'Fırın'], [
    i('Kuzu kuşbaşı', '1 kg', '🍖', 'meat'), i('Yoğurt', '600 g', '🥛', 'dairy'), i('Yumurta', '3 adet', '🥚', 'egg'), i('Un', '2 yemek kaşığı', '🌾', 'grain'), i('Tereyağı', '3 yemek kaşığı', '🧈', 'dairy'), i('Sarımsak', '3 diş', '🧄', 'vegetable'), i('Et suyu', '2 su bardağı', '🥣', 'other'), i('Karabiber', '1 çay kaşığı', '🌶️', 'spice'),
  ], [
    'Kuzu etini bir kaşık tereyağında yüksek ateşte renk alana kadar mühürleyin.',
    'Et suyunu ekleyip kapağı kapalı olarak kısık ateşte et yumuşayana kadar 45-55 dakika pişirin.',
    'Eti süzüp fırın kabına yayın; pişirme suyundan bir su bardağını ayırın.',
    'Yoğurt, yumurta, un, ezilmiş sarımsak, tuz ve ayrılan ılık et suyunu pürüzsüz olana dek çırpın.',
    'Karışımı etlerin üzerine dökün ve kalan tereyağını küçük parçalar halinde yüzeye dağıtın.',
    '190°C fırında terbiye tutup üstü altın rengi olana kadar 30-35 dakika pişirin.',
    'Fırından çıktıktan sonra 10 dakika dinlendirip karabiber serperek servis edin.',
  ]),
  r('Firik Pilavı', 'İsli aromalı firik buğdayının bulgur ve nohutla ağır ağır pişirildiği Güneydoğu pilavı.', 'Pilav', '🍚', '55 dk', '6 kişilik', ['Gaziantep', 'Firik', 'Bulgur', 'Nohut'], [
    i('Firik bulguru', '2 su bardağı', '🌾', 'grain'), i('Pilavlık bulgur', '1 su bardağı', '🌾', 'grain'), i('Haşlanmış nohut', '1 su bardağı', '🫘', 'vegetable'), i('Tereyağı', '3 yemek kaşığı', '🧈', 'dairy'), i('Et suyu', '5 su bardağı', '🥣', 'other'), i('Kuru soğan', '1 adet', '🧅', 'vegetable'), i('Karabiber', '1 çay kaşığı', '🌶️', 'spice'), i('Pul biber', '1 çay kaşığı', '🌶️', 'spice'),
  ], [
    'Firiği taş ve kabuklarından ayıklayın; iki kez yıkayıp süzün.',
    'Soğanı ince doğrayın ve tereyağında saydamlaşana kadar 4-5 dakika kavurun.',
    'Firik ile pilavlık bulguru ekleyip taneler yağla kaplanana kadar 3 dakika çevirin.',
    'Haşlanmış nohudu, karabiberi, pul biberi ve sıcak et suyunu ekleyip karıştırın.',
    'Kaynadığında kapağı kapatın ve en kısık ateşte suyunu çekene kadar 25-30 dakika pişirin.',
    'Ocağı kapatıp kapak altına temiz bez yerleştirerek pilavı 15 dakika demlendirin.',
    'Taneleri ezmeden havalandırın; yanında yoğurt veya et yemeğiyle sıcak servis edin.',
  ]),
  r('Hasanpaşa Köftesi', 'Çanak biçimli köftelerin patates püresiyle doldurulup domates sosuyla fırınlandığı klasik ev yemeği.', 'Ana Yemek', '🥩', '1 sa 10 dk', '6 kişilik', ['Köfte', 'Patates', 'Fırın', 'Ev Yemeği'], [
    i('Dana kıyma', '700 g', '🥩', 'meat'), i('Kuru soğan', '1 adet', '🧅', 'vegetable'), i('Galeta unu', 'yarım su bardağı', '🌾', 'grain'), i('Yumurta', '1 adet', '🥚', 'egg'), i('Patates', '5 adet', '🥔', 'vegetable'), i('Süt', '1 su bardağı', '🥛', 'dairy'), i('Tereyağı', '2 yemek kaşığı', '🧈', 'dairy'), i('Domates salçası', '1,5 yemek kaşığı', '🍅', 'vegetable'), i('Kaşar peyniri', '100 g', '🧀', 'dairy'),
  ], [
    'Kıyma, rendelenip suyu sıkılmış soğan, galeta unu, yumurta, tuz ve karabiberi 8 dakika yoğurun.',
    'Harcı altı parçaya ayırın; ortaları çukur, kenarları yüksek köfte çanakları hazırlayın.',
    'Köfteleri 200°C fırında 15 dakika ön pişirmeye alın.',
    'Patatesleri haşlayıp ezin; sıcak süt, tereyağı ve tuzla pürüzsüz bir püre hazırlayın.',
    'Salçayı bir su bardağı sıcak suyla açıp fırın kabının tabanına dökün.',
    'Köfte çanaklarını püreyle doldurun, üzerlerine rendelenmiş kaşar serpin.',
    '190°C fırında peynir kızarıp sos koyulaşana kadar 20-25 dakika daha pişirin.',
  ]),
  r('Haşhaşlı Çörek', 'İnce açılan mayalı hamurun ezilmiş haşhaşla katlanıp burgu biçiminde pişirildiği Anadolu çöreği.', 'Hamur İşi', '🥐', '2 sa', '8 kişilik', ['Afyon', 'Haşhaş', 'Çörek', 'Kahvaltı'], [
    i('Un', '700 g', '🌾', 'grain'), i('Ilık süt', '300 ml', '🥛', 'dairy'), i('Kuru maya', '10 g', '🧂', 'other'), i('Yumurta', '2 adet', '🥚', 'egg'), i('Haşhaş ezmesi', '250 g', '🌰', 'nut'), i('Ayçiçek yağı', '1 su bardağı', '🫗', 'oil'), i('Toz şeker', '2 yemek kaşığı', '🍬', 'other'),
  ], [
    'Ilık süt, maya ve şekeri karıştırıp maya köpürene kadar 10 dakika bekletin.',
    'Un, bir yumurta, bir çay kaşığı tuz ve mayalı karışımı yumuşak bir hamur olana kadar yoğurun.',
    'Hamuru örtüp hacmi iki katına çıkana kadar yaklaşık 50 dakika mayalandırın.',
    'Haşhaş ezmesini yağla sürülebilir kıvama gelene kadar karıştırın.',
    'Hamuru dikdörtgen açın; haşhaşı yüzeye yayın, üçe katlayıp şeritler kesin.',
    'Şeritleri burarak tepsiye dizin ve 20 dakika tepsi mayası yaptırın.',
    'Kalan yumurtayı sürüp 190°C fırında 25-30 dakika koyu altın rengi olana kadar pişirin.',
  ]),
  r('Islama Köfte', 'Izgara köfte ve kemik suyuna batırılmış kızarmış ekmek katlarıyla hazırlanan Sakarya lezzeti.', 'Ana Yemek', '🥩', '1 sa', '4 kişilik', ['Sakarya', 'Köfte', 'Ekmek', 'Izgara'], [
    i('Dana kıyma', '600 g', '🥩', 'meat'), i('Bayat ekmek içi', '2 dilim', '🍞', 'grain'), i('Kuru soğan', '1 adet', '🧅', 'vegetable'), i('Kemik suyu', '3 su bardağı', '🥣', 'other'), i('Tırnak pide', '2 adet', '🫓', 'grain'), i('Tereyağı', '2 yemek kaşığı', '🧈', 'dairy'), i('Toz kırmızı biber', '1 tatlı kaşığı', '🌶️', 'spice'), i('Kimyon', '1 çay kaşığı', '🌿', 'spice'),
  ], [
    'Kıyma, ıslatılıp sıkılmış ekmek, rendelenmiş soğan, kimyon, tuz ve karabiberi iyice yoğurun.',
    'Harçtan yassı, parmak uzunluğunda köfteler hazırlayıp buzdolabında 20 dakika dinlendirin.',
    'Kemik suyunu ısıtın; tereyağı ve kırmızı biber ekleyip 5 dakika hafifçe kaynatın.',
    'Pideleri dilimleyin, her iki yüzünü ızgarada hafifçe kızartın.',
    'Ekmekleri sıcak kemik suyuna kısa süre batırıp süzdürerek servis tabağına kat kat dizin.',
    'Köfteleri kızgın ızgara ya da döküm tavada her yüzü kızarana kadar pişirin.',
    'Köfteleri ıslatılmış ekmeklerin üzerine yerleştirip közlenmiş domates ve biberle servis edin.',
  ]),
  r('İskilip Dolması', 'Dana eti üzerinde saatlerce buharla pişen pirincin et suyuyla buluştuğu Çorum düğün yemeği.', 'Ana Yemek', '🍚', '4 sa', '8 kişilik', ['Çorum', 'Pilav', 'Dana Eti', 'Düğün Yemeği'], [
    i('Dana eti', '1,5 kg iri parça', '🥩', 'meat'), i('Pirinç', '4 su bardağı', '🍚', 'grain'), i('Kuru soğan', '3 adet', '🧅', 'vegetable'), i('Tereyağı', '200 g', '🧈', 'dairy'), i('Et suyu', '7 su bardağı', '🥣', 'other'), i('Tuz', '2 tatlı kaşığı', '🧂', 'other'), i('Karabiber', '1 tatlı kaşığı', '🌶️', 'spice'),
  ], [
    'Eti iri parçalara ayırıp geniş tencerenin dibinde tereyağının yarısıyla renk alana kadar kavurun.',
    'Soğanın yarısını ekleyin, üzerine sıcak su koyup et yumuşayana kadar yaklaşık 2 saat pişirin.',
    'Pirinci ılık tuzlu suda 30 dakika bekletin; yıkayıp süzdükten sonra kalan soğan ve yağla kavurun.',
    'Pirinci temiz pamuklu bez torbaya gevşekçe doldurun ve ağzını bağlayın; şişme payı bırakın.',
    'Etli tencerenin üstüne buhar sepeti yerleştirip pirinç torbasını koyun; kapağı hamurla sıkıca kapatın.',
    'Pilavı etin buharında kısık ateşte 1,5-2 saat pişirin; gerekirse et suyunu kontrol edin.',
    'Pirinci tepsiye yayıp et suyuyla tane tane açın; ortasına etleri koyup karabiberle servis edin.',
  ]),
  r('Kaburga Dolması', 'Kuzu kaburgasının baharatlı bademli iç pilavla doldurulup ağır ağır pişirildiği Güneydoğu şöleni.', 'Ana Yemek', '🍖', '3 sa 30 dk', '8 kişilik', ['Mardin', 'Kuzu', 'İç Pilav', 'Özel Gün'], [
    i('Kuzu kaburga', '2,5 kg cepli', '🍖', 'meat'), i('Pirinç', '2,5 su bardağı', '🍚', 'grain'), i('Badem', 'yarım su bardağı', '🥜', 'nut'), i('Kuş üzümü', '3 yemek kaşığı', '🍇', 'fruit'), i('Kuru soğan', '2 adet', '🧅', 'vegetable'), i('Tereyağı', '100 g', '🧈', 'dairy'), i('Yenibahar', '1 tatlı kaşığı', '🌶️', 'spice'), i('Tarçın', 'yarım çay kaşığı', '🌿', 'spice'), i('Et suyu', '3 su bardağı', '🥣', 'other'),
  ], [
    'Kasabınızdan kaburganın et ile kemik arasını cep biçiminde açmasını isteyin; içini ve dışını tuzlayın.',
    'Soğan ve bademi tereyağında kavurun; yıkanmış pirinç, kuş üzümü ve baharatları ekleyin.',
    'İki su bardağı et suyu ekleyip pilavı suyunu yarı çekene kadar 8-10 dakika pişirin.',
    'Ilık iç pilavı kaburga cebine gevşekçe doldurun ve açıklığı kalın mutfak ipiyle sıkıca dikin.',
    'Kaburgayı geniş tencerede her yüzü renk alana kadar mühürleyin; kalan et suyunu ekleyin.',
    'Kapalı tencerede çok kısık ateşte 2 saat pişirin, ardından fırın kabına alın.',
    '200°C fırında dışı kızarana kadar 30-40 dakika pişirip 15 dakika dinlendirdikten sonra dilimleyin.',
  ]),
  r('Kayseri Yağlaması', 'İncecik şebit ekmeklerinin kıymalı domates sosuyla katlandığı, sarımsaklı yoğurtla sunulan Kayseri yemeği.', 'Ana Yemek', '🫓', '1 sa 40 dk', '6 kişilik', ['Kayseri', 'Şebit', 'Kıymalı', 'Yoğurtlu'], [
    i('Un', '600 g', '🌾', 'grain'), i('Ilık su', '320 ml', '💧', 'other'), i('Kuru maya', '7 g', '🧂', 'other'), i('Dana kıyma', '500 g', '🥩', 'meat'), i('Kuru soğan', '2 adet', '🧅', 'vegetable'), i('Domates', '4 adet', '🍅', 'vegetable'), i('Domates salçası', '1 yemek kaşığı', '🍅', 'vegetable'), i('Yoğurt', '400 g', '🥛', 'dairy'), i('Sarımsak', '3 diş', '🧄', 'vegetable'),
  ], [
    'Un, maya, ılık su ve tuzla yumuşak bir hamur yoğurun; 40 dakika mayalandırın.',
    'Hamuru 12 bezeye ayırın, her birini servis tabağı büyüklüğünde çok ince açın.',
    'Şebitleri yağsız kızgın tavada iki yüzünde benekler oluşana kadar pişirip örtü altında tutun.',
    'Kıymayı kavurun; soğanı, salçayı ve rendelenmiş domatesi ekleyip sulu bir harç hazırlayın.',
    'Her şebidin üzerine sıcak kıymalı harç yayın ve üst üste katlayın.',
    'Katlı yağlamayı dört üçgen parçaya kesip tabaklara paylaştırın.',
    'Ezilmiş sarımsakla karıştırılmış yoğurdu ortasına koyup sıcak servis edin.',
  ]),
  r('Keledoş', 'Döğme, nohut, mercimek ve kurutun kuzu etiyle birleştiği Van yöresine ait doyurucu yemek.', 'Ana Yemek', '🥣', '2 sa', '6 kişilik', ['Van', 'Kurut', 'Bakliyat', 'Kuzu'], [
    i('Kuzu kuşbaşı', '500 g', '🍖', 'meat'), i('Döğme buğday', '1 su bardağı', '🌾', 'grain'), i('Haşlanmış nohut', '1 su bardağı', '🫘', 'vegetable'), i('Yeşil mercimek', 'yarım su bardağı', '🫘', 'vegetable'), i('Kurut', '150 g', '🥛', 'dairy'), i('Pazı', '1 bağ', '🥬', 'vegetable'), i('Tereyağı', '3 yemek kaşığı', '🧈', 'dairy'), i('Kuru soğan', '1 adet', '🧅', 'vegetable'),
  ], [
    'Döğmeyi geceden suya yatırın; ertesi gün süzüp taze suyla yumuşayana kadar haşlayın.',
    'Kuzu etini ayrı tencerede suyunu salıp çekene kadar kavurun, sıcak su ekleyip yumuşatın.',
    'Yeşil mercimeği ayrı kapta diri kalacak biçimde haşlayıp süzün.',
    'Et, döğme, nohut ve mercimeği aynı tencerede birleştirip 15 dakika kaynatın.',
    'Doğranmış pazıyı ekleyin; kurutu ılık yemek suyuyla ezip pürüzsüzleştirerek tencereye katın.',
    'Kısık ateşte kesilmemesi için karıştırarak 10-12 dakika pişirin ve tuzunu ayarlayın.',
    'Soğanı tereyağında kızartıp yemeğin üzerine gezdirin; sıcak servis edin.',
  ]),
  r('Konya Fırın Kebabı', 'Kuzu etinin bakır kapta, kendi yağıyla saatlerce fırınlanarak lokum gibi piştiği Konya kebabı.', 'Ana Yemek', '🍖', '4 sa', '6 kişilik', ['Konya', 'Kuzu', 'Fırın', 'Geleneksel'], [
    i('Kuzu kol', '1,5 kg kemikli', '🍖', 'meat'), i('Kuzu kaburga', '700 g', '🍖', 'meat'), i('Kuyruk yağı', '100 g', '🥩', 'meat'), i('Tuz', '2 tatlı kaşığı', '🧂', 'other'), i('Su', 'yarım su bardağı', '💧', 'other'), i('Tırnak pide', '2 adet', '🫓', 'grain'), i('Kuru soğan', '2 adet', '🧅', 'vegetable'),
  ], [
    'Kuzu kol ve kaburgayı iri kemikli parçalara ayırıp yüzeylerini iyice kurulayın.',
    'Kalın tabanlı kapaklı fırın kabının dibine kuyruk yağını yayın ve etleri üzerine yerleştirin.',
    'Tuzu ve suyu ekleyin; kabın kapağını buhar kaçırmayacak biçimde kapatın.',
    '150°C fırında eti çevirmeden yaklaşık 3 saat ağır ağır pişirin.',
    'Kapağı açıp etleri nazikçe çevirin; 200°C’de 25-35 dakika dışlarını kızartın.',
    'Etleri 15 dakika dinlendirip kemikten ayrılan iri parçalar halinde porsiyonlayın.',
    'Isıtılmış tırnak pide ve kuru soğanla, pişirme yağından az miktar gezdirerek servis edin.',
  ]),
  r('Laz Böreği', 'İnce yufka katları arasında karabiberle dengelenen muhallebi bulunan şerbetli Karadeniz tatlısı.', 'Tatlı', '🍰', '1 sa 30 dk', '10 kişilik', ['Karadeniz', 'Muhallebi', 'Şerbetli', 'Yufka'], [
    i('Baklavalık yufka', '20 yaprak', '🌾', 'grain'), i('Süt', '1 litre', '🥛', 'dairy'), i('Yumurta sarısı', '3 adet', '🥚', 'egg'), i('Un', '3 yemek kaşığı', '🌾', 'grain'), i('Nişasta', '3 yemek kaşığı', '🌾', 'grain'), i('Toz şeker', '2,5 su bardağı', '🍬', 'other'), i('Tereyağı', '180 g', '🧈', 'dairy'), i('Karabiber', 'yarım çay kaşığı', '🌶️', 'spice'), i('Limon suyu', '1 tatlı kaşığı', '🍋', 'fruit'),
  ], [
    'Bir buçuk su bardağı şeker, iki su bardağı su ve limon suyunu 10 dakika kaynatıp soğutun.',
    'Süt, yumurta sarısı, kalan şeker, un ve nişastayı çırparak koyu muhallebi olana kadar pişirin.',
    'Muhallebiye karabiber ekleyip yüzeyini kapatarak tamamen ılıtın.',
    'Tepsiyi yağlayın; yufkaların yarısını aralarına eritilmiş tereyağı sürerek katlayın.',
    'Muhallebiyi eşit yayın, kalan yufkaları da aynı şekilde üzerine yerleştirip dilimleyin.',
    '180°C fırında katlar çıtır ve koyu altın rengi olana kadar 35-40 dakika pişirin.',
    'Sıcak böreğe soğuk şerbeti dökün; en az 2 saat dinlendirip servis edin.',
  ]),
  r('Nevzine Tatlısı', 'Tahinli ve cevizli hamurun pekmezli şerbetle buluştuğu Kayseri’ye özgü yoğun aromalı tatlı.', 'Tatlı', '🍰', '1 sa 15 dk', '10 kişilik', ['Kayseri', 'Tahin', 'Pekmez', 'Ceviz'], [
    i('Un', '4 su bardağı', '🌾', 'grain'), i('Tahin', '1 su bardağı', '🥜', 'nut'), i('Tereyağı', '150 g', '🧈', 'dairy'), i('Yoğurt', '1 çay bardağı', '🥛', 'dairy'), i('Ceviz', '1,5 su bardağı', '🌰', 'nut'), i('Üzüm pekmezi', '1 su bardağı', '🍇', 'other'), i('Toz şeker', '1,5 su bardağı', '🍬', 'other'), i('Kabartma tozu', '10 g', '🧂', 'other'),
  ], [
    'Şeker ve iki su bardağı suyu 10 dakika kaynatın; ocaktan alınca pekmezi karıştırıp soğutun.',
    'Eritilmiş tereyağı, tahin ve yoğurdu geniş kapta homojen olana kadar karıştırın.',
    'Un ve kabartma tozunu azar azar ekleyip ele yapışmayan yumuşak bir hamur hazırlayın.',
    'İri çekilmiş cevizi hamura katıp fazla yoğurmadan eşit dağıtın.',
    'Hamuru yağlanmış tepsiye bastırarak yayın; yüzeyini çatalla desenleyip baklava dilimi kesin.',
    '180°C fırında üzeri iyice kızarana kadar 35-40 dakika pişirin.',
    'Fırından çıkan sıcak tatlıya soğuk pekmezli şerbeti döküp 3 saat dinlendirin.',
  ]),
  r('Paçanga Böreği', 'Pastırma, kaşar, domates ve biberin yufkaya sarılıp çıtır kızartıldığı sıcak başlangıç.', 'Hamur İşi', '🥟', '35 dk', '6 kişilik', ['Börek', 'Pastırma', 'Kaşar', 'Kızartma'], [
    i('Yufka', '3 adet', '🌾', 'grain'), i('Pastırma', '180 g', '🥩', 'meat'), i('Kaşar peyniri', '250 g', '🧀', 'dairy'), i('Domates', '2 adet', '🍅', 'vegetable'), i('Yeşil biber', '3 adet', '🌶️', 'vegetable'), i('Ayçiçek yağı', '2 su bardağı', '🫗', 'oil'), i('Un', '1 yemek kaşığı', '🌾', 'grain'),
  ], [
    'Domateslerin çekirdekli sulu kısmını çıkarıp küçük küp, biberleri ince doğrayın.',
    'Pastırmayı şeritler halinde kesin; kaşarı rendeleyip tüm iç malzemeyi karıştırın.',
    'Her yufkayı dört eşit üçgen parçaya bölerek toplam 12 parça hazırlayın.',
    'Geniş kenara iç harç koyun; yanları içe katlayıp sıkı ama yırtmadan sarın.',
    'Uç kısmını un ve suyla hazırlanan koyu karışıma batırarak yapıştırın.',
    'Börekleri 175°C kızgın yağda çevirerek her tarafı altın rengi olana kadar kızartın.',
    'Kâğıt havlu yerine tel ızgarada kısa süre süzdürüp sıcak servis edin.',
  ]),
  r('Patates Oturtma', 'Kızarmış patates dilimlerinin kıymalı domates harcıyla katlanıp fırınlandığı ev yemeği.', 'Ana Yemek', '🥔', '1 sa 15 dk', '6 kişilik', ['Patates', 'Kıymalı', 'Fırın', 'Ev Yemeği'], [
    i('Patates', '6 büyük adet', '🥔', 'vegetable'), i('Dana kıyma', '400 g', '🥩', 'meat'), i('Kuru soğan', '2 adet', '🧅', 'vegetable'), i('Domates', '3 adet', '🍅', 'vegetable'), i('Domates salçası', '1 yemek kaşığı', '🍅', 'vegetable'), i('Sivri biber', '3 adet', '🌶️', 'vegetable'), i('Ayçiçek yağı', '1,5 su bardağı', '🫗', 'oil'), i('Sarımsak', '2 diş', '🧄', 'vegetable'),
  ], [
    'Patatesleri soyup bir santimetre kalınlığında halka dilimleyin ve iyice kurulayın.',
    'Patatesleri kızgın yağda tamamen yumuşatmadan hafif renk alana kadar kızartıp süzün.',
    'Kıymayı tavada suyunu çekene kadar kavurun; soğan, biber ve sarımsağı ekleyin.',
    'Salça ve doğranmış domatesi katıp harcı 10 dakika pişirin; tuz ve karabiberle tatlandırın.',
    'Fırın kabına patates ve kıymalı harcı dönüşümlü katlar halinde yerleştirin.',
    'Bir su bardağı sıcak su ekleyip kabın üzerini ilk 20 dakika kapatın.',
    '190°C fırında toplam 35-40 dakika, patatesler tamamen yumuşayana kadar pişirin.',
  ]),
  r('Siron', 'Rulo yufka dilimlerinin sarımsaklı yoğurt ve tereyağlı sosla yumuşatıldığı Karadeniz yemeği.', 'Ana Yemek', '🫓', '45 dk', '6 kişilik', ['Gümüşhane', 'Yufka', 'Yoğurtlu', 'Tereyağlı'], [
    i('Kuru yufka', '4 adet', '🌾', 'grain'), i('Yoğurt', '600 g', '🥛', 'dairy'), i('Sarımsak', '4 diş', '🧄', 'vegetable'), i('Tereyağı', '4 yemek kaşığı', '🧈', 'dairy'), i('Toz kırmızı biber', '1 tatlı kaşığı', '🌶️', 'spice'), i('Sıcak su', '1,5 su bardağı', '💧', 'other'), i('Tuz', '1 tatlı kaşığı', '🧂', 'other'),
  ], [
    'Kuru yufkaları hafifçe nemlendirip üst üste koyun ve sıkı rulolar halinde sarın.',
    'Ruloları iki parmak kalınlığında kesip kesik yüzleri yukarı gelecek biçimde tepsiye sıkıca dizin.',
    'Yufkaları 180°C fırında kenarları hafif kızarana kadar 10-12 dakika ısıtın.',
    'Sıcak suyu azar azar gezdirip tepsiyi kapatın ve yufkaların 8 dakika yumuşamasını bekleyin.',
    'Yoğurdu ezilmiş sarımsak ve tuzla çırpıp ılık yufkaların üzerine eşitçe yayın.',
    'Tereyağını köpürtüp kırmızı biberi yakmadan ekleyin.',
    'Biberli yağı yoğurdun üzerine gezdirip bekletmeden servis edin.',
  ]),
  r('Şambali', 'İrmik ve yoğurtla hazırlanan yoğun dokulu kekin limonlu şerbet ve fıstıkla tamamlandığı İzmir tatlısı.', 'Tatlı', '🍰', '1 sa 10 dk', '12 kişilik', ['İzmir', 'İrmik', 'Şerbetli', 'Sokak Lezzeti'], [
    i('İrmik', '3 su bardağı', '🌾', 'grain'), i('Yoğurt', '1,5 su bardağı', '🥛', 'dairy'), i('Toz şeker', '3 su bardağı', '🍬', 'other'), i('Karbonat', '1 tatlı kaşığı', '🧂', 'other'), i('Yer fıstığı', 'yarım su bardağı', '🥜', 'nut'), i('Limon suyu', '1 yemek kaşığı', '🍋', 'fruit'), i('Pekmez', '1 yemek kaşığı', '🍇', 'other'),
  ], [
    'İki su bardağı şeker, iki buçuk su bardağı su ve limon suyunu 12 dakika kaynatıp soğutun.',
    'İrmik, kalan şeker, yoğurt ve karbonatı spatulayla koyu bir harç olana kadar karıştırın.',
    'Tepsiyi pekmezle ince biçimde yağlayın; harcı iki santimetre kalınlığında bastırarak yayın.',
    'Yüzeyi ıslak spatulayla düzeltin, dikdörtgen dilimleri çizip her birine fıstık yerleştirin.',
    'Harç irmiğin şişmesi için oda sıcaklığında 30 dakika dinlensin.',
    '180°C fırında kenarları ve üstü koyu altın rengi olana kadar 35-40 dakika pişirin.',
    'Sıcak tatlıya soğuk şerbeti dökün; tamamen çekmesi için en az 4 saat bekletin.',
  ]),
  r('Tire Köftesi', 'İnce uzun köftelerin tereyağlı domates sosunda pide ve yoğurtla sunulduğu Tire lezzeti.', 'Ana Yemek', '🥩', '50 dk', '4 kişilik', ['İzmir', 'Tire', 'Köfte', 'Domates Soslu'], [
    i('Dana kıyma', '600 g', '🥩', 'meat'), i('Tuz', '1 tatlı kaşığı', '🧂', 'other'), i('Domates', '5 adet', '🍅', 'vegetable'), i('Tereyağı', '3 yemek kaşığı', '🧈', 'dairy'), i('Tırnak pide', '1 adet', '🫓', 'grain'), i('Yoğurt', '300 g', '🥛', 'dairy'), i('Yeşil biber', '4 adet', '🌶️', 'vegetable'),
  ], [
    'Kıyma ve tuzu en az 8 dakika, lifli ve yapışkan bir kıvam alana kadar yoğurun.',
    'Harçtan ceviz büyüklüğünde parçalar alıp parmak kalınlığında uzun köfteler şekillendirin.',
    'Köfteleri şişlere dizip buzdolabında 20 dakika dinlendirin.',
    'Döküm tava veya ızgarada köfteleri çevirerek her yüzü kızarana kadar pişirin.',
    'Rendelenmiş domatesi tereyağında suyunun bir kısmı çekilene kadar 8-10 dakika pişirin.',
    'Küp doğranmış pideyi tabağa yayın; köfteleri koyup sıcak domates sosunu gezdirin.',
    'Közlenmiş biber ve yanında çırpılmış yoğurtla hemen servis edin.',
  ]),
  r('Tokat Kebabı', 'Kuzu eti, patlıcan, patates ve biberin özel düzende şişlenip fırınlandığı Tokat yemeği.', 'Ana Yemek', '🍢', '1 sa 45 dk', '6 kişilik', ['Tokat', 'Kuzu', 'Sebzeli', 'Fırın'], [
    i('Kuzu kuşbaşı', '900 g', '🍖', 'meat'), i('Patlıcan', '4 adet', '🍆', 'vegetable'), i('Patates', '4 adet', '🥔', 'vegetable'), i('Domates', '4 adet', '🍅', 'vegetable'), i('Yeşil biber', '6 adet', '🌶️', 'vegetable'), i('Sarımsak', '1 baş', '🧄', 'vegetable'), i('Kuyruk yağı', '100 g', '🥩', 'meat'), i('Tuz', '2 tatlı kaşığı', '🧂', 'other'),
  ], [
    'Patlıcanları kalın halka kesin, tuzlu suda 20 dakika bekletip kurulayın.',
    'Patatesleri patlıcanlarla aynı kalınlıkta halka, domates ve biberleri iri parçalar halinde kesin.',
    'Uzun şişlere patlıcan, kuzu eti, patates ve kuyruk yağını dönüşümlü ve sıkı biçimde dizin.',
    'Şişleri derin fırın kabının üzerine asın; alta domates, biber ve kabuklu sarımsakları yayın.',
    'Et ve sebzeleri tuzlayıp kabın üzerini ilk 50 dakika kapatın.',
    '200°C fırında toplam 75-90 dakika; son bölümde açık olarak yüzeyler kızarana kadar pişirin.',
    'Şişleri sebzelerin üzerine sıyırın, tepside biriken lezzetli suyla sıcak servis edin.',
  ]),
  r('Yalancı Dolma', 'Etsiz, bol soğanlı ve baharatlı pirinç harcının asma yaprağına sarıldığı zeytinyağlı dolma.', 'Zeytinyağlı', '🍃', '1 sa 30 dk', '8 kişilik', ['Zeytinyağlı', 'Yaprak Sarma', 'Etsiz', 'Meze'], [
    i('Salamura asma yaprağı', '500 g', '🍃', 'vegetable'), i('Pirinç', '2 su bardağı', '🍚', 'grain'), i('Kuru soğan', '4 adet', '🧅', 'vegetable'), i('Zeytinyağı', '1 su bardağı', '🫒', 'oil'), i('Dolmalık fıstık', '2 yemek kaşığı', '🥜', 'nut'), i('Kuş üzümü', '2 yemek kaşığı', '🍇', 'fruit'), i('Yenibahar', '1 çay kaşığı', '🌶️', 'spice'), i('Kuru nane', '1 yemek kaşığı', '🌿', 'spice'), i('Limon', '1 adet', '🍋', 'fruit'),
  ], [
    'Yaprakları fazla tuzunu almak için sıcak suda 5 dakika bekletip soğuk sudan geçirin.',
    'İnce doğranmış soğan ve fıstığı zeytinyağının yarısında yumuşayana kadar kavurun.',
    'Pirinç, kuş üzümü ve baharatları ekleyip iki su bardağı sıcak suyla yarı diri pişirin.',
    'Yaprakların damarlı yüzüne birer tatlı kaşığı iç koyup ince, sıkı rulolar sarın.',
    'Tencere tabanını yaprakla kaplayın; dolmaları dikiş yeri alta gelecek biçimde dizin.',
    'Kalan yağ, limon dilimleri ve dolmaların hizasına kadar sıcak su ekleyip tabakla bastırın.',
    'Kısık ateşte 40 dakika pişirin; tencerede tamamen soğutup limonla servis edin.',
  ]),
  r('Yuvalama', 'Nohut ve kuzu etiyle pişen minik pirinç köftelerinin yoğurtlu terbiyeyle birleştiği Gaziantep yemeği.', 'Çorba', '🥣', '2 sa 30 dk', '8 kişilik', ['Gaziantep', 'Yoğurtlu', 'Köfteli', 'Bayram'], [
    i('Pirinç unu', '2 su bardağı', '🍚', 'grain'), i('Yağsız kıyma', '250 g', '🥩', 'meat'), i('Kuzu kuşbaşı', '500 g', '🍖', 'meat'), i('Haşlanmış nohut', '1,5 su bardağı', '🫘', 'vegetable'), i('Süzme yoğurt', '750 g', '🥛', 'dairy'), i('Yumurta', '1 adet', '🥚', 'egg'), i('Un', '1 yemek kaşığı', '🌾', 'grain'), i('Tereyağı', '3 yemek kaşığı', '🧈', 'dairy'), i('Kuru nane', '1 yemek kaşığı', '🌿', 'spice'),
  ], [
    'Pirinç unu, yağsız kıyma, tuz ve az suyu macun kıvamına gelene kadar uzun süre yoğurun.',
    'Ellerinizi yağlayıp harçtan nohut tanesinden küçük köfteler yuvarlayın ve unlu tepsiye alın.',
    'Kuzu etini tencerede yumuşayana kadar haşlayın; haşlanmış nohudu ve köfteleri ekleyin.',
    'Köfteler yüzeye çıkıp pişene kadar yemeği kısık ateşte 12-15 dakika kaynatın.',
    'Yoğurt, yumurta ve unu çırpın; sıcak et suyuyla aşamalı olarak ılıştırın.',
    'Yoğurt terbiyesini tencereye ince akıtarak ekleyin ve kaynama noktasına kadar sürekli karıştırın.',
    'Tereyağında naneyi köpürtüp üzerine gezdirin; tuzunu ayarlayarak sıcak servis edin.',
  ]),
  r('Ayran Aşı Çorbası', 'Buğday, nohut, yoğurt ve taze otlarla hazırlanan ferahlatıcı soğuk yaz çorbası.', 'Çorba', '🥣', '45 dk', '6 kişilik', ['Soğuk Çorba', 'Yoğurt', 'Buğday', 'Yaz'], [
    i('Aşurelik buğday', '1,5 su bardağı', '🌾', 'grain'), i('Haşlanmış nohut', '1 su bardağı', '🫘', 'vegetable'), i('Yoğurt', '750 g', '🥛', 'dairy'), i('Soğuk su', '3 su bardağı', '💧', 'other'), i('Taze nane', 'yarım demet', '🌿', 'spice'), i('Dereotu', 'yarım demet', '🌿', 'vegetable'), i('Salatalık', '2 adet', '🥒', 'vegetable'), i('Tuz', '1 tatlı kaşığı', '🧂', 'other'),
  ], [
    'Buğdayı geceden ıslatın; ertesi gün bol suda taneler açılıp yumuşayana kadar haşlayın.',
    'Haşlanan buğdayı süzüp tamamen soğutun; sıcak malzeme yoğurdu kesebilir.',
    'Yoğurdu pürüzsüz olana kadar çırpın ve soğuk suyu azar azar ekleyerek ayran kıvamına getirin.',
    'Soğuk buğday ve haşlanmış nohudu yoğurt karışımına katın.',
    'Salatalığı küçük küp doğrayın; nane ve dereotunu ince kıyıp çorbaya ekleyin.',
    'Tuzunu ayarlayıp buzdolabında en az 1 saat soğutun.',
    'Kıvam koyulaşırsa soğuk suyla açıp buz küpleri ve taze otlarla servis edin.',
  ]),
  r('Besmeç', 'İnce bulgur ve kıymanın baharatlarla yoğrulup yassı köfte halinde pişirildiği Kırşehir yemeği.', 'Ana Yemek', '🥩', '50 dk', '6 kişilik', ['Kırşehir', 'Bulgur', 'Köfte', 'Tava'], [
    i('Dana kıyma', '500 g', '🥩', 'meat'), i('İnce bulgur', '1,5 su bardağı', '🌾', 'grain'), i('Kuru soğan', '2 adet', '🧅', 'vegetable'), i('Yumurta', '1 adet', '🥚', 'egg'), i('Domates salçası', '1 yemek kaşığı', '🍅', 'vegetable'), i('Pul biber', '1 tatlı kaşığı', '🌶️', 'spice'), i('Kimyon', '1 çay kaşığı', '🌿', 'spice'), i('Ayçiçek yağı', 'yarım su bardağı', '🫗', 'oil'),
  ], [
    'İnce bulguru yarım su bardağı sıcak suyla ıslatıp kapalı olarak 15 dakika şişirin.',
    'Soğanı çok ince rendeleyin ve fazla suyunu hafifçe sıkın.',
    'Bulgur, kıyma, soğan, yumurta, salça ve baharatları 10 dakika güçlü biçimde yoğurun.',
    'Harçtan mandalina büyüklüğünde parçalar alıp bir santimetre kalınlığında yassı köfteler hazırlayın.',
    'Köfteleri buzdolabında 20 dakika dinlendirerek biçimlerinin sabitlenmesini sağlayın.',
    'Az yağlı geniş tavada orta ateşte her yüzünü 4-5 dakika kızartın.',
    'İçinin tamamen piştiğini kontrol edip soğan salatası ve ayranla sıcak servis edin.',
  ]),
  r('Peynir Helvası', 'Tuzsuz taze peynirin irmik, tereyağı ve şekerle kavrulduğu sıcak servis edilen yöresel tatlı.', 'Tatlı', '🧀', '40 dk', '6 kişilik', ['Çanakkale', 'Peynir', 'Helva', 'Sıcak Tatlı'], [
    i('Tuzsuz taze peynir', '500 g', '🧀', 'dairy'), i('İrmik', '1 su bardağı', '🌾', 'grain'), i('Toz şeker', '1,5 su bardağı', '🍬', 'other'), i('Tereyağı', '80 g', '🧈', 'dairy'), i('Yumurta sarısı', '1 adet', '🥚', 'egg'), i('Su', 'yarım su bardağı', '💧', 'other'),
  ], [
    'Tuzsuz taze peyniri elinizle ufalayın; fazla suyu varsa süzgeçte 15 dakika bekletin.',
    'Tereyağını kalın tabanlı tavada eritin ve irmiği ekleyin.',
    'İrmiği orta-kısık ateşte kokusu çıkıp açık altın rengi alana kadar sürekli karıştırarak kavurun.',
    'Peyniri ekleyip eriyerek uzayan, homojen bir karışım olana kadar ezerek karıştırın.',
    'Şeker ve suyu ilave edin; şeker eriyip karışım yeniden koyulaşana kadar pişirin.',
    'Ocaktan almaya yakın yumurta sarısını hızla karıştırarak yedirin ve 2 dakika daha pişirin.',
    'Helvayı küçük güveçlere paylaştırıp sıcak veya üzeri kısa süre kızartılmış olarak servis edin.',
  ]),
  r('Fırında Makarna', 'Beşamel sos ve peynirle katlanan makarnanın üzeri kızarana kadar fırınlandığı klasik Türk ev yemeği.', 'Ana Yemek', '🍝', '1 sa', '8 kişilik', ['Makarna', 'Beşamel', 'Fırın', 'Ev Yemeği'], [
    i('Kalın çubuk makarna', '500 g', '🍝', 'grain'), i('Süt', '1 litre', '🥛', 'dairy'), i('Un', '4 yemek kaşığı', '🌾', 'grain'), i('Tereyağı', '4 yemek kaşığı', '🧈', 'dairy'), i('Yumurta', '2 adet', '🥚', 'egg'), i('Beyaz peynir', '250 g', '🧀', 'dairy'), i('Kaşar peyniri', '250 g', '🧀', 'dairy'), i('Muskat', 'çeyrek çay kaşığı', '🌰', 'spice'),
  ], [
    'Makarnayı bol tuzlu kaynar suda paket süresinden iki dakika kısa haşlayıp iyice süzün.',
    'Tereyağını tencerede eritin; unu ekleyip rengi değişmeden kokusu çıkana kadar 2-3 dakika kavurun.',
    'Sütü azar azar eklerken tel çırpıcıyla karıştırın; pürüzsüz ve akışkan beşamel hazırlayın.',
    'Sosa tuz, karabiber ve muskat ekleyin; birkaç dakika ılınınca çırpılmış yumurtaları hızla yedirin.',
    'Makarnayı beşamelin üçte ikisi ve ufalanmış beyaz peynirle nazikçe karıştırıp yağlanmış kaba yayın.',
    'Kalan beşameli yüzeye dökün ve rendelenmiş kaşar peynirini her yere eşit dağıtın.',
    '190°C fırında üstü koyu altın rengi olana kadar 25-30 dakika pişirin; dilimlemeden önce 15 dakika dinlendirin.',
  ]),
  r('Kıbrıs Tatlısı', 'Cevizli ve galeta unlu kekin şerbet, vanilyalı muhallebi ve Hindistan ceviziyle katlandığı tatlı.', 'Tatlı', '🍰', '1 sa 20 dk', '10 kişilik', ['Şerbetli', 'Muhallebili', 'Ceviz', 'Hindistan Cevizi'], [
    i('Yumurta', '3 adet', '🥚', 'egg'), i('Galeta unu', '1 su bardağı', '🌾', 'grain'), i('Hindistan cevizi', '1 su bardağı', '🥥', 'nut'), i('Ceviz', '1 su bardağı', '🌰', 'nut'), i('Toz şeker', '2,5 su bardağı', '🍬', 'other'), i('Süt', '1 litre', '🥛', 'dairy'), i('Nişasta', '2 yemek kaşığı', '🌾', 'grain'), i('Un', '2 yemek kaşığı', '🌾', 'grain'), i('Krema', '200 ml', '🥛', 'dairy'),
  ], [
    'Bir buçuk su bardağı şeker ve iki su bardağı suyu 10 dakika kaynatıp soğumaya bırakın.',
    'Yumurta ve yarım su bardağı şekeri kabarana kadar çırpın; galeta unu, Hindistan cevizi ve cevizi katın.',
    'Harcı yağlanmış orta boy kaba yayın ve 175°C fırında 25-30 dakika pişirin.',
    'Fırından çıkan sıcak kekin üzerine soğuk şerbeti eşitçe döküp çekmesini bekleyin.',
    'Süt, kalan şeker, un ve nişastayı koyulaşana kadar pişirip tamamen ılıtın.',
    'Kremayı muhallebiye çırparak yedirin ve şerbetli tabanın üzerine düzgünce yayın.',
    'Hindistan cevizi serpip buzdolabında en az 4 saat dinlendirdikten sonra dilimleyin.',
  ]),
  r('Samsun Kaz Tiridi', 'Kaz eti ve suyuyla ıslatılan yufkanın bulgur pilavıyla katlandığı Samsun’un kış yemeği.', 'Ana Yemek', '🍗', '3 sa', '8 kişilik', ['Samsun', 'Kaz', 'Tirit', 'Bulgur'], [
    i('Kaz eti', '2 kg parça', '🍗', 'meat'), i('Kuru yufka', '5 adet', '🌾', 'grain'), i('Pilavlık bulgur', '2 su bardağı', '🌾', 'grain'), i('Kaz suyu', '5 su bardağı', '🥣', 'other'), i('Kuru soğan', '2 adet', '🧅', 'vegetable'), i('Kaz yağı', '4 yemek kaşığı', '🫗', 'oil'), i('Tuz', '2 tatlı kaşığı', '🧂', 'other'), i('Karabiber', '1 tatlı kaşığı', '🌶️', 'spice'),
  ], [
    'Kaz parçalarını tuzlayıp tencereye alın; üzerini geçecek suyla yumuşayana kadar yaklaşık 2 saat haşlayın.',
    'Eti çıkarıp kemiklerinden ayırın; haşlama suyunu süzün ve yüzeyde biriken kaz yağını ayırın.',
    'Soğanı iki kaşık kaz yağında kavurun; bulguru ekleyip sıcak kaz suyuyla tane tane pişirin.',
    'Kuru yufkaları üçgen parçalara ayırıp fırında hafifçe gevrekleştirin.',
    'Yufkaları sıcak kaz suyuna kısa süre batırıp geniş servis tepsisine kat kat yayın.',
    'Bulgur pilavını yufkaların ortasına, didiklenmiş kaz etini pilavın üzerine yerleştirin.',
    'Kalan kızgın kaz yağını gezdirip karabiber serpin ve sıcak servis edin.',
  ]),
  r('Sinop Mantısı', 'Küçük hamur bohçalarının kıymayla doldurulup bir yarısının ceviz, diğer yarısının yoğurtla sunulduğu mantı.', 'Ana Yemek', '🥟', '1 sa 45 dk', '6 kişilik', ['Sinop', 'Mantı', 'Ceviz', 'Yoğurtlu'], [
    i('Un', '500 g', '🌾', 'grain'), i('Yumurta', '2 adet', '🥚', 'egg'), i('Su', '180 ml', '💧', 'other'), i('Dana kıyma', '300 g', '🥩', 'meat'), i('Kuru soğan', '1 adet', '🧅', 'vegetable'), i('Yoğurt', '400 g', '🥛', 'dairy'), i('Sarımsak', '3 diş', '🧄', 'vegetable'), i('Ceviz', '1 su bardağı', '🌰', 'nut'), i('Tereyağı', '3 yemek kaşığı', '🧈', 'dairy'),
  ], [
    'Un, yumurta, su ve tuzla sertçe bir hamur yoğurup kapalı olarak 30 dakika dinlendirin.',
    'Kıyma, çok ince doğranmış soğan, tuz ve karabiberi çiğden karıştırın.',
    'Hamuru ince açın ve üç santimetrelik karelere kesin; ortalarına az kıymalı harç koyun.',
    'Karşılıklı köşeleri ortada birleştirerek küçük kapalı bohçalar hazırlayın.',
    'Mantıları kaynar tuzlu suda hamur yumuşayıp iç pişene kadar 8-10 dakika haşlayıp süzün.',
    'Mantının yarısına sarımsaklı yoğurt, diğer yarısına iri çekilmiş ceviz yayın.',
    'Köpürtülmüş tereyağını tamamının üzerine gezdirip sıcak servis edin.',
  ]),
  r('Dalyan Köfte', 'Yumurta, havuç ve bezelyeyi saran büyük rulo köftenin domates sosuyla fırınlandığı davet yemeği.', 'Ana Yemek', '🥩', '1 sa 30 dk', '8 kişilik', ['Rulo Köfte', 'Yumurta', 'Fırın', 'Davet'], [
    i('Dana kıyma', '1 kg', '🥩', 'meat'), i('Kuru soğan', '2 adet', '🧅', 'vegetable'), i('Galeta unu', '1 su bardağı', '🌾', 'grain'), i('Yumurta', '5 adet', '🥚', 'egg'), i('Havuç', '2 adet', '🥕', 'vegetable'), i('Bezelye', '1 su bardağı', '🫛', 'vegetable'), i('Domates salçası', '2 yemek kaşığı', '🍅', 'vegetable'), i('Ayçiçek yağı', '2 yemek kaşığı', '🫗', 'oil'),
  ], [
    'Üç yumurtayı katı haşlayın; havuçları çubuk doğrayıp bezelyeyle birlikte diri haşlayın.',
    'Kıyma, rendelenmiş soğan, galeta unu, iki çiğ yumurta, tuz ve baharatları iyice yoğurun.',
    'Köfte harcını yağlı kâğıt üzerinde iki santimetre kalınlığında dikdörtgen açın.',
    'Ortaya haşlanmış yumurta, havuç ve bezelyeyi sıra halinde yerleştirin.',
    'Kâğıttan yardım alarak eti sıkı rulo sarın, birleşim yerini ve uçlarını kapatın.',
    '190°C fırında 35 dakika pişirin; salçalı sıcak sosu üzerine sürün.',
    '15 dakika daha kızartın, fırından sonra 10 dakika dinlendirip kalın dilimleyin.',
  ]),
  r('İslim Kebabı', 'Kızarmış patlıcan şeritlerinin köfteyi bohça gibi sardığı, domates ve biberle fırınlanan kebap.', 'Ana Yemek', '🍆', '1 sa 20 dk', '6 kişilik', ['Patlıcan', 'Köfte', 'Fırın', 'Kebap'], [
    i('Patlıcan', '5 adet', '🍆', 'vegetable'), i('Dana kıyma', '600 g', '🥩', 'meat'), i('Kuru soğan', '1 adet', '🧅', 'vegetable'), i('Galeta unu', 'yarım su bardağı', '🌾', 'grain'), i('Domates', '3 adet', '🍅', 'vegetable'), i('Yeşil biber', '6 adet', '🌶️', 'vegetable'), i('Domates salçası', '1 yemek kaşığı', '🍅', 'vegetable'), i('Ayçiçek yağı', '1 su bardağı', '🫗', 'oil'),
  ], [
    'Patlıcanları uzunlamasına yarım santimetre kalınlığında dilimleyip tuzlu suda 20 dakika bekletin.',
    'Kuruladığınız patlıcan dilimlerini az yağda esnekleşip hafif renk alana kadar kızartın.',
    'Kıyma, rendelenmiş soğan, galeta unu, tuz ve baharatları yoğurup altı iri köfte hazırlayın.',
    'Köfteleri tavada yalnızca dışları renk alacak biçimde kısa süre mühürleyin.',
    'İki patlıcan dilimini artı biçiminde koyup ortasına köfte yerleştirin ve uçları kapatın.',
    'Üstlerine domates ve biber koyup kürdanla sabitleyin; salçalı sıcak suyu kaba dökün.',
    '190°C fırında köfteler tamamen pişip sos koyulaşana kadar 30-35 dakika pişirin.',
  ]),
  r('Manisa Kebabı', 'Küçük köftelerin pide, yoğurt ve tereyağlı domates sosuyla buluştuğu Manisa usulü kebap.', 'Ana Yemek', '🥩', '55 dk', '6 kişilik', ['Manisa', 'Köfte', 'Pide', 'Yoğurtlu'], [
    i('Dana kıyma', '700 g', '🥩', 'meat'), i('Kuru soğan', '1 adet', '🧅', 'vegetable'), i('Galeta unu', 'yarım su bardağı', '🌾', 'grain'), i('Tırnak pide', '2 adet', '🫓', 'grain'), i('Yoğurt', '400 g', '🥛', 'dairy'), i('Domates', '4 adet', '🍅', 'vegetable'), i('Tereyağı', '4 yemek kaşığı', '🧈', 'dairy'), i('Yeşil biber', '5 adet', '🌶️', 'vegetable'),
  ], [
    'Kıyma, rendelenmiş soğan, galeta unu, tuz ve karabiberi yoğurup küçük uzun köfteler hazırlayın.',
    'Köfteleri buzdolabında 20 dakika dinlendirin; bu sırada pideleri küçük küpler halinde kesin.',
    'Pide küplerini tavada bir kaşık tereyağıyla hafifçe kızartıp tabaklara paylaştırın.',
    'Köfteleri kızgın döküm tavada çevirerek tamamen pişirin; biberleri yanında közleyin.',
    'Rendelenmiş domatesi iki kaşık tereyağında koyulaşana kadar pişirip tuzlayın.',
    'Pidelerin üzerine çırpılmış yoğurt, ardından sıcak domates sosu ve köfteleri yerleştirin.',
    'Kalan tereyağını köpürtüp gezdirin; köz biberlerle hemen servis edin.',
  ]),
  r('Tekirdağ Köftesi', 'İrmik ve baharatla uzun süre yoğrulup dinlendirilen, ızgarada pişen Tekirdağ köftesi.', 'Ana Yemek', '🥩', '13 sa', '6 kişilik', ['Tekirdağ', 'Köfte', 'Izgara', 'Dinlendirilmiş'], [
    i('Dana kıyma', '1 kg orta yağlı', '🥩', 'meat'), i('İrmik', '3 yemek kaşığı', '🌾', 'grain'), i('Kuru soğan', '1 adet', '🧅', 'vegetable'), i('Sarımsak', '2 diş', '🧄', 'vegetable'), i('Karbonat', '1 çay kaşığı', '🧂', 'other'), i('Kimyon', '1 tatlı kaşığı', '🌿', 'spice'), i('Karabiber', '1 çay kaşığı', '🌶️', 'spice'), i('Tuz', '1,5 tatlı kaşığı', '🧂', 'other'),
  ], [
    'Kıymayı geniş tepsiye yayın; irmik, karbonat, kimyon, karabiber ve tuzu ekleyin.',
    'Soğanı rendeleyip suyunu sıkın, sarımsağı ezin ve kıymaya katın.',
    'Harcı avuç içiyle bastırıp katlayarak en az 12 dakika, yapışkan kıvam alana kadar yoğurun.',
    'Üzerini kapatıp buzdolabında en az 12 saat dinlendirerek lezzetin oturmasını sağlayın.',
    'Harçtan eşit parçalar alıp ıslak elle kısa ve yassı parmak köfteler biçimlendirin.',
    'Çok sıcak ızgarada iki yüzünü de çizgili kızaracak ve içi pişecek şekilde çevirerek pişirin.',
    'Közlenmiş biber, domates, soğan ve Tekirdağ usulü acı sosla sıcak servis edin.',
  ]),
  r('Çöp Şiş', 'Küçük kuzu eti parçalarının kısa şişlerde domates ve biberle hızlıca ızgara edildiği Ege kebabı.', 'Ana Yemek', '🍢', '2 sa 30 dk', '4 kişilik', ['Aydın', 'Kuzu', 'Şiş', 'Izgara'], [
    i('Kuzu but', '700 g', '🍖', 'meat'), i('Kuyruk yağı', '100 g', '🥩', 'meat'), i('Zeytinyağı', '3 yemek kaşığı', '🫒', 'oil'), i('Yoğurt', '2 yemek kaşığı', '🥛', 'dairy'), i('Kekik', '1 tatlı kaşığı', '🌿', 'spice'), i('Arpacık soğan', '12 adet', '🧅', 'vegetable'), i('Çeri domates', '12 adet', '🍅', 'vegetable'), i('Sivri biber', '6 adet', '🌶️', 'vegetable'),
  ], [
    'Kuzu etini yaklaşık iki santimetrelik eşit küçük küpler halinde kesin.',
    'Zeytinyağı, yoğurt, kekik ve karabiberi karıştırıp eti bu terbiyede 2 saat dinlendirin.',
    'Ahşap kısa şişleri yanmamaları için 30 dakika suda bekletin.',
    'Şişlere üç-dört et parçası ve aralara küçük kuyruk yağı parçaları dizin.',
    'Izgarayı çok iyi ısıtın; şişleri sık çevirerek dışları kızarıp içi sulu kalacak biçimde pişirin.',
    'Domates, biber ve arpacık soğanları ayrı şişlerde közleyip son aşamada tuzlayın.',
    'Çöp şişleri lavaş üzerinde köz sebzeler, sumaklı soğan ve ayranla servis edin.',
  ]),
  r('Mısır Ekmeği', 'Mısır unu ve yoğurtla hazırlanan, dışı kızarmış içi nemli geleneksel Karadeniz ekmeği.', 'Hamur İşi', '🍞', '55 dk', '8 kişilik', ['Karadeniz', 'Mısır Unu', 'Ekmek', 'Glutensiz Seçenek'], [
    i('Mısır unu', '4 su bardağı', '🌽', 'grain'), i('Yoğurt', '1 su bardağı', '🥛', 'dairy'), i('Sıcak su', '2 su bardağı', '💧', 'other'), i('Zeytinyağı', 'yarım su bardağı', '🫒', 'oil'), i('Kabartma tozu', '10 g', '🧂', 'other'), i('Tuz', '1 tatlı kaşığı', '🧂', 'other'), i('Tereyağı', '1 yemek kaşığı', '🧈', 'dairy'),
  ], [
    'Mısır unu, kabartma tozu ve tuzu geniş bir kapta homojen biçimde karıştırın.',
    'Yoğurt ve zeytinyağını ekleyip tahta kaşıkla mısır ununa yedirin.',
    'Sıcak suyu azar azar ilave ederek koyu kek hamuru kıvamında bir karışım hazırlayın.',
    'Döküm tava veya küçük tepsiyi tereyağıyla bolca yağlayıp fırında 5 dakika ısıtın.',
    'Harcı sıcak kaba dökün, ıslak spatulayla yüzeyi eşit kalınlıkta düzeltin.',
    '200°C fırında kenarlar koyu kızarıp ortasına batırılan kürdan temiz çıkana kadar 35-40 dakika pişirin.',
    'Ekmeği kalıpta 15 dakika dinlendirip dilimleyin; çorba veya yoğurtla servis edin.',
  ]),
  r('Belen Tava', 'Kuzu eti, domates, biber ve sarımsağın tereyağıyla taş fırın lezzetinde piştiği Hatay yemeği.', 'Ana Yemek', '🍖', '1 sa 15 dk', '6 kişilik', ['Hatay', 'Kuzu', 'Sebzeli', 'Fırın'], [
    i('Kuzu kuşbaşı', '1 kg küçük doğranmış', '🍖', 'meat'), i('Domates', '5 adet', '🍅', 'vegetable'), i('Kapya biber', '2 adet', '🫑', 'vegetable'), i('Yeşil biber', '5 adet', '🌶️', 'vegetable'), i('Kuru soğan', '2 adet', '🧅', 'vegetable'), i('Sarımsak', '6 diş', '🧄', 'vegetable'), i('Tereyağı', '100 g', '🧈', 'dairy'), i('Pul biber', '1 tatlı kaşığı', '🌶️', 'spice'),
  ], [
    'Kuzu etini olabildiğince küçük küpler halinde doğrayıp geniş bakır veya fırın tepsisine yayın.',
    'Soğan, domates ve biberleri küçük doğrayın; sarımsakları ince dilimleyin.',
    'Tüm sebzeleri etle birlikte tuz, karabiber ve pul biber kullanarak tepside karıştırın.',
    'Karışımı eşit kalınlıkta yayın ve tereyağını küçük parçalar halinde yüzeye dağıtın.',
    'Tepsiyi yağlı kâğıt ve folyo ile kapatıp 200°C fırında 40 dakika pişirin.',
    'Örtüyü kaldırın; et yumuşayıp sebze suyu koyulaşana kadar 20-25 dakika daha kızartın.',
    'Tepsideki suyuyla birlikte lavaş, maydanoz ve sumaklı soğan eşliğinde sıcak servis edin.',
  ]),
  r('Kerebiç', 'İrmikli hamurun Antep fıstığı veya cevizle doldurulup çöven köpüğüyle sunulduğu Mersin tatlısı.', 'Tatlı', '🥟', '1 sa 30 dk', '10 kişilik', ['Mersin', 'İrmik', 'Antep Fıstığı', 'Çöven'], [
    i('İrmik', '3 su bardağı', '🌾', 'grain'), i('Un', '1 su bardağı', '🌾', 'grain'), i('Tereyağı', '200 g', '🧈', 'dairy'), i('Süt', 'yarım su bardağı', '🥛', 'dairy'), i('Antep fıstığı', '1,5 su bardağı', '🥜', 'nut'), i('Pudra şekeri', 'yarım su bardağı', '🍬', 'other'), i('Tarçın', '1 çay kaşığı', '🌿', 'spice'), i('Çöven köpüğü', '500 g', '🍬', 'other'),
  ], [
    'İrmik, un ve pudra şekerini karıştırın; eritilip ılıtılmış tereyağını ekleyerek ovun.',
    'Sütü azar azar katıp çatlamadan şekil alan yumuşak bir hamur hazırlayın ve 30 dakika dinlendirin.',
    'İnce çekilmiş Antep fıstığını tarçınla karıştırarak iç harcı hazırlayın.',
    'Hamurdan ceviz büyüklüğünde parçalar alıp oyun; iç koyup kapatarak oval biçim verin.',
    'Kerebiç kalıbına bastırıp desen verin ve yağlı kâğıtlı tepsiye aralıklı dizin.',
    '175°C fırında üzerleri koyulaşmadan tabanları hafif kızarana kadar 20-25 dakika pişirin.',
    'Tamamen soğuyan kerebiçleri geleneksel çöven köpüğüyle birlikte servis edin.',
  ]),
  r('Deniz Börülcesi', 'Kıyı otunun sarımsak, limon ve zeytinyağıyla harmanlandığı ferah Ege mezesi.', 'Meze', '🥗', '35 dk', '4 kişilik', ['Ege', 'Deniz Börülcesi', 'Zeytinyağlı', 'Meze'], [
    i('Deniz börülcesi', '2 bağ', '🌿', 'vegetable'), i('Sarımsak', '3 diş', '🧄', 'vegetable'), i('Zeytinyağı', '5 yemek kaşığı', '🫒', 'oil'), i('Limon suyu', '3 yemek kaşığı', '🍋', 'fruit'), i('Üzüm sirkesi', '1 yemek kaşığı', '🍇', 'other'), i('Karabiber', 'yarım çay kaşığı', '🌶️', 'spice'),
  ], [
    'Deniz börülcelerini bol suda birkaç kez yıkayarak kumdan tamamen arındırın.',
    'Geniş tencerede tuz eklemeden bol su kaynatın; börülceleri 8-10 dakika haşlayın.',
    'Yumuşayan börülceleri buzlu suya alarak pişmeyi durdurun ve rengini koruyun.',
    'Her dalı kök ucundan tutup etli kısmını sıyırarak sert orta lifinden ayırın.',
    'Ezilmiş sarımsak, zeytinyağı, limon suyu, sirke ve karabiberi çırpın.',
    'Sosu börülcelerle nazikçe karıştırın; bitkinin doğal tuzu nedeniyle tadına bakmadan tuz eklemeyin.',
    'Buzdolabında 30 dakika dinlendirip soğuk meze olarak servis edin.',
  ]),
  r('Enginar Dolması', 'Bütün enginarların pirinçli, otlu ve zeytinyağlı içle doldurulduğu Ege usulü bahar yemeği.', 'Zeytinyağlı', '🌿', '1 sa 20 dk', '6 kişilik', ['Ege', 'Enginar', 'Zeytinyağlı', 'Dolma'], [
    i('Bütün enginar', '6 adet', '🌿', 'vegetable'), i('Pirinç', '1,5 su bardağı', '🍚', 'grain'), i('Taze soğan', '1 demet', '🧅', 'vegetable'), i('Dereotu', 'yarım demet', '🌿', 'vegetable'), i('Taze nane', 'yarım demet', '🌿', 'spice'), i('Zeytinyağı', '1 su bardağı', '🫒', 'oil'), i('Limon', '2 adet', '🍋', 'fruit'), i('Toz şeker', '1 tatlı kaşığı', '🍬', 'other'),
  ], [
    'Enginarların dıştaki sert yapraklarını ayırın, uçlarını kesin ve iç tüylü kısmını kaşıkla temizleyin.',
    'Kararmamaları için temizlenen enginarları limonlu suda bekletin.',
    'Pirinç, doğranmış taze soğan, dereotu, nane, tuz, şeker ve zeytinyağının yarısını karıştırın.',
    'İç harcı enginarların merkezine ve gevşetilmiş yaprak aralarına çok sıkıştırmadan doldurun.',
    'Enginarları dik biçimde tencereye yerleştirin; kalan yağ, limon suyu ve yarılarına gelecek sıcak suyu ekleyin.',
    'Üzerlerine ıslak pişirme kâğıdı kapatıp kısık ateşte yapraklar kolay ayrılana kadar 45-50 dakika pişirin.',
    'Tenceresinde soğutup dereotu ve limon dilimleriyle oda sıcaklığında servis edin.',
  ]),
  r('Çökelekli Pide', 'Baharatlı çökelek ve yeşillik harcının ince hamur üzerinde taş fırın lezzetinde piştiği Anadolu pidesi.', 'Hamur İşi', '🥙', '1 sa 35 dk', '6 kişilik', ['Pide', 'Çökelek', 'Fırın', 'Vejetaryen'], [
    i('Un', '600 g', '🌾', 'grain'), i('Ilık su', '350 ml', '💧', 'other'), i('Kuru maya', '7 g', '🧂', 'other'), i('Çökelek', '400 g', '🧀', 'dairy'), i('Kuru soğan', '1 adet', '🧅', 'vegetable'), i('Maydanoz', 'yarım demet', '🌿', 'vegetable'), i('Pul biber', '1 tatlı kaşığı', '🌶️', 'spice'), i('Zeytinyağı', '3 yemek kaşığı', '🫒', 'oil'), i('Tereyağı', '2 yemek kaşığı', '🧈', 'dairy'),
  ], [
    'Un, maya, ılık su ve tuzu birleştirip pürüzsüz ve yumuşak bir hamur yoğurun.',
    'Hamuru örtüp 45 dakika mayalandırın, ardından altı eşit bezeye ayırın.',
    'Çökelek, ince doğranmış soğan, maydanoz, pul biber ve zeytinyağını karıştırın.',
    'Bezeleri unlu zeminde uzun ve ince oval biçimde açın.',
    'Harcı ortalarına yayın; kenarları içe kıvırıp uçları birleştirerek kayık şekli verin.',
    'Önceden ısıtılmış 240°C fırında tabanı ve kenarları kızarana kadar 10-12 dakika pişirin.',
    'Fırından çıkan sıcak pidelerin kenarlarına tereyağı sürüp dilimleyerek servis edin.',
  ]),
  r('Kuzu Güveç', 'Kuzu eti ve mevsim sebzelerinin toprak kapta kendi suyuyla ağır ağır piştiği geleneksel ana yemek.', 'Ana Yemek', '🍲', '2 sa 15 dk', '6 kişilik', ['Kuzu', 'Güveç', 'Sebzeli', 'Fırın'], [
    i('Kuzu kuşbaşı', '1 kg', '🍖', 'meat'), i('Patlıcan', '3 adet', '🍆', 'vegetable'), i('Domates', '5 adet', '🍅', 'vegetable'), i('Yeşil biber', '5 adet', '🌶️', 'vegetable'), i('Kuru soğan', '2 adet', '🧅', 'vegetable'), i('Sarımsak', '6 diş', '🧄', 'vegetable'), i('Tereyağı', '3 yemek kaşığı', '🧈', 'dairy'), i('Domates salçası', '1 yemek kaşığı', '🍅', 'vegetable'), i('Kekik', '1 tatlı kaşığı', '🌿', 'spice'),
  ], [
    'Patlıcanları iri küp doğrayıp tuzlu suda 20 dakika bekletin; süzüp kurulayın.',
    'Kuzu etini çok kızgın tavada partiler halinde yalnızca dışı renk alana kadar mühürleyin.',
    'Toprak güvecin dibine soğan ve sarımsağı, üzerine et, patlıcan ve biberleri katlayın.',
    'Salçayı bir su bardağı sıcak suyla açıp tuz, karabiber ve kekikle birlikte güvece dökün.',
    'Domatesleri en üste yayın, tereyağını küçük parçalar halinde dağıtın ve kapağı kapatın.',
    '180°C fırında yaklaşık 90 dakika, et ve sebzeler tamamen yumuşayana kadar pişirin.',
    'Kapağı açıp 15 dakika daha kızartın; güveci 10 dakika dinlendirerek sıcak servis edin.',
  ]),
];
